name: Hello World Docker Action
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  docker_workflow_action:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.0.2
      
      - name: Run my own container action
        id: hello-action
        uses: ./hello-world-docker-action
        with:
          who-to-greet: 'huhuIchbineinHuhu'
      
      - name: Output time set in the container
        run: echo "The time was ${{ steps.hello-action.outputs.time }} when the action said hello"
